app:
  name: "mielLinkServer"
  mode: "dev"
  port: 9090
  salt: "testsalt"

jwt:
  secret: "testsecret"
  issuer: "mielLinkServer"

mysql:
  host: "127.0.0.1"
  port: 3337
  user: "root"
  password: "miellink"
  charset: "utf8mb4"
  db: "miellink"